In [1]:
#Forward substitution

In [3]:
import numpy as np

def forward_substitution(L, b):
    n = L.shape[0]
    x = np.zeros_like(b, dtype=float)
    
    for i in range(n):
        sum_ = sum(L[i, j] * x[j] for j in range(i))
        x[i] = (b[i] - sum_) / L[i, i]
    
    return x

# Example: Solve Lx = b
L = np.array([
    [2, 0, 0],
    [3, 1, 0],
    [1, -4, 5]
], dtype=float)

b = np.array([4, 5, -2], dtype=float)

x = forward_substitution(L, b)

print("Solution x:")
print(x)


Solution x:
[ 2.  -1.  -1.6]


In [5]:
#Backward substitution

In [7]:
import numpy as np

def backward_substitution(U, b):
    n = U.shape[0]
    x = np.zeros_like(b, dtype=float)

    for i in range(n - 1, -1, -1):  # loop from n-1 down to 0
        sum_ = sum(U[i, j] * x[j] for j in range(i + 1, n))
        x[i] = (b[i] - sum_) / U[i, i]

    return x

# Example: Solve Ux = b
U = np.array([
    [2, -1, 3],
    [0, 1, -2],
    [0, 0, 4]
], dtype=float)

b = np.array([5, -1, 8], dtype=float)

x = backward_substitution(U, b)

print("Solution x:")
print(x)


Solution x:
[1. 3. 2.]


In [9]:
#LU decomposition

In [11]:
import numpy as np

def lu_decomposition(A):
    n = A.shape[0]
    L = np.zeros_like(A, dtype=float)
    U = np.zeros_like(A, dtype=float)

    for i in range(n):
        # Upper triangular matrix U
        for j in range(i, n):
            U[i, j] = A[i, j] - np.dot(L[i, :i], U[:i, j])

        # Lower triangular matrix L
        for j in range(i + 1, n):
            L[j, i] = (A[j, i] - np.dot(L[j, :i], U[:i, i])) / U[i, i]

        L[i, i] = 1  # Set diagonal of L to 1

    return L, U

# Example matrix A
A = np.array([
    [2, -1, 1],
    [3, 3, 9],
    [3, 3, 5]
], dtype=float)

L, U = lu_decomposition(A)

print("L matrix:")
print(L)
print("\nU matrix:")
print(U)

# Verify: A ≈ L @ U
print("\nReconstruction A ≈ L @ U:")
print(np.round(L @ U, decimals=6))


L matrix:
[[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]]

U matrix:
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]

Reconstruction A ≈ L @ U:
[[ 2. -1.  1.]
 [ 3.  3.  9.]
 [ 3.  3.  5.]]


In [13]:
#PLU decomposition

In [15]:
import numpy as np

def plu_decomposition(A):
    A = A.astype(float)
    n = A.shape[0]
    P = np.eye(n)  # Start with identity matrix for P
    L = np.zeros_like(A, dtype=float)
    U = A.copy()

    for i in range(n):
        # Pivoting: Find the maximum value in column i (partial pivoting)
        max_index = np.argmax(np.abs(U[i:n, i])) + i
        if max_index != i:
            # Swap rows i and max_index in U
            U[[i, max_index]] = U[[max_index, i]]
            # Swap corresponding rows in P
            P[[i, max_index]] = P[[max_index, i]]
            # Record the row swaps in L
            L[[i, max_index], :i] = L[[max_index, i], :i]

        # Decompose into L and U
        for j in range(i + 1, n):
            L[j, i] = U[j, i] / U[i, i]
            U[j, i:] = U[j, i:] - L[j, i] * U[i, i:]

    # Fill the diagonal of L with 1s
    np.fill_diagonal(L, 1)
    
    return P, L, U

# Example matrix A
A = np.array([
    [2, -1, 1],
    [3, 3, 9],
    [3, 3, 5]
], dtype=float)

P, L, U = plu_decomposition(A)

print("P matrix (Permutation):")
print(P)
print("\nL matrix (Lower Triangular):")
print(L)
print("\nU matrix (Upper Triangular):")
print(U)

# Verify: A ≈ P @ L @ U
print("\nReconstruction A ≈ P @ L @ U:")
print(np.round(P @ L @ U, decimals=6))


P matrix (Permutation):
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]

L matrix (Lower Triangular):
[[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [ 1.         -0.          1.        ]]

U matrix (Upper Triangular):
[[ 3.  3.  9.]
 [ 0. -3. -5.]
 [ 0.  0. -4.]]

Reconstruction A ≈ P @ L @ U:
[[ 2. -1.  1.]
 [ 3.  3.  9.]
 [ 3.  3.  5.]]


In [17]:
#Cholesky decomposition

In [19]:
import numpy as np

# Example symmetric positive-definite matrix A
A = np.array([
    [4, 2],
    [2, 2]
], dtype=float)

# Cholesky Decomposition (A = L * L^T)
L = np.linalg.cholesky(A)

print("L matrix (Lower Triangular):")
print(L)

# Verify: A ≈ L @ L.T
print("\nReconstruction A ≈ L @ L^T:")
print(np.round(L @ L.T, decimals=6))


L matrix (Lower Triangular):
[[2. 0.]
 [1. 1.]]

Reconstruction A ≈ L @ L^T:
[[4. 2.]
 [2. 2.]]
