In [1]:
#REF and RREF

In [3]:
from sympy import Matrix

# Define a 4x4 matrix
A = Matrix([
    [1, 2, 3, 4],
    [2, 4, 6, 8],
    [3, 6, 2, 1],
    [4, 8, 3, 7]
])

# Compute REF (Row Echelon Form)
ref_matrix, _ = A.echelon_form(with_pivots=True)

# Compute RREF (Reduced Row Echelon Form)
rref_matrix, pivot_columns = A.rref()

# Display the results
print("Original Matrix:")
print(A)

print("\nREF (Row Echelon Form):")
print(ref_matrix)

print("\nRREF (Reduced Row Echelon Form):")
print(rref_matrix)

print("\nPivot Columns in RREF:")
print(pivot_columns)


Original Matrix:
Matrix([[1, 2, 3, 4], [2, 4, 6, 8], [3, 6, 2, 1], [4, 8, 3, 7]])

REF (Row Echelon Form):
Matrix([[1, 2, 3, 4], [0, 0, -7, -11], [0, 0, 0, -36], [0, 0, 0, 0]])

RREF (Reduced Row Echelon Form):
Matrix([[1, 2, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [0, 0, 0, 0]])

Pivot Columns in RREF:
(0, 2, 3)


In [5]:
#Rank and nullity

In [7]:
from sympy import Matrix

# Define the matrix
A = Matrix([
    [1, 2, 3, 4],
    [2, 4, 6, 8],
    [3, 6, 2, 1],
    [4, 8, 3, 7]
])

# Rank of the matrix
rank = A.rank()

# Nullity = number of columns - rank
nullity = A.cols - rank

print("Rank:", rank)
print("Nullity:", nullity)


Rank: 3
Nullity: 1


In [14]:
#Compute all four fundamental subspaces

In [16]:
from sympy import Matrix

# Define the matrix A
A = Matrix([
    [1, 2, 3, 4],
    [2, 4, 6, 8],
    [3, 6, 2, 1],
    [4, 8, 3, 7]
])

# Column Space (Range of A)
col_space = A.columnspace()

# Null Space (Kernel of A)
null_space = A.nullspace()

# Row Space (Range of A^T)
row_space = A.transpose().columnspace()

# Left Null Space (Kernel of A^T)
left_null_space = A.transpose().nullspace()

# Display Results
print("Column Space (Basis):")
for vec in col_space:
    print(vec)

print("\nNull Space (Basis):")
for vec in null_space:
    print(vec)

print("\nRow Space (Basis):")
for vec in row_space:
    print(vec)

print("\nLeft Null Space (Basis):")
for vec in left_null_space:
    print(vec)


Column Space (Basis):
Matrix([[1], [2], [3], [4]])
Matrix([[3], [6], [2], [3]])
Matrix([[4], [8], [1], [7]])

Null Space (Basis):
Matrix([[-2], [1], [0], [0]])

Row Space (Basis):
Matrix([[1], [2], [3], [4]])
Matrix([[3], [6], [2], [1]])
Matrix([[4], [8], [3], [7]])

Left Null Space (Basis):
Matrix([[-2], [1], [0], [0]])


In [18]:
#various norms of matrix

In [20]:
import numpy as np

# Define your matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=float)

# Frobenius norm (default for 'np.linalg.norm' with a matrix)
fro_norm = np.linalg.norm(A, 'fro')

# L1 norm (maximum absolute column sum)
l1_norm = np.linalg.norm(A, 1)

# L∞ norm (maximum absolute row sum)
linf_norm = np.linalg.norm(A, np.inf)

# 2-norm (largest singular value)
l2_norm = np.linalg.norm(A, 2)

print("Frobenius Norm:", fro_norm)
print("L1 Norm (max column sum):", l1_norm)
print("Infinity Norm (max row sum):", linf_norm)
print("2-Norm (spectral norm):", l2_norm)

Frobenius Norm: 16.881943016134134
L1 Norm (max column sum): 18.0
Infinity Norm (max row sum): 24.0
2-Norm (spectral norm): 16.84810335261421


In [22]:
#matrix addition, transpose, multiplication

In [24]:
import numpy as np

# Define matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix Addition
add = A + B

# Transpose of A
transpose_A = A.T

# Matrix Multiplication
product = np.dot(A, B)  # or A @ B

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nAddition A + B:\n", add)
print("\nTranspose of A:\n", transpose_A)
print("\nMultiplication A * B:\n", product)


Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]

Addition A + B:
 [[ 6  8]
 [10 12]]

Transpose of A:
 [[1 3]
 [2 4]]

Multiplication A * B:
 [[19 22]
 [43 50]]
